### ISSUE TITLE
Sync up the PHP demo with the python demo

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellowdemo-php#2]
We usually update the [python demo](https://github.com/YellowPay/yellowdemo) first, and it's about time to sync them up. Biggest changes are:
- We dropped the "redirect" checkbox 
- We added some more currencies to the currecny drop down
- we added support for different types of invoices (the link invoice type is still in final testing and hasn't been deployed yet - so it's worht updating the demo now, but we'll hold off deploying until everything is setup)

**Comment by mahmoud200m** [comment]
I can't understand this point
`we added support for different types of invoices (the link invoice type is still in final testing and hasn't been deployed yet - so it's worht updating the demo now, but we'll hold off deploying until everything is setup)`

**Comment by JamesPiechota** [comment]
Ah, Yeah you'll notice in the python demo that there's a drop down for type of invoice: https://github.com/YellowPay/yellowdemo/blob/master/demo/templates/demo/create.html#L40-L44

It gets processed and turned into a 'type' parameter to be passed to the API:
https://github.com/YellowPay/yellowdemo/blob/master/demo/views.py#L39-L40

We haven't actually deployed the code to handle the 'type' parameter yet (although it should work in your local deve environment). So as you're building the PHP demo, don't worry if the 'link' type doesn't work as expected. Once we deploy everything to production, the demo should work.

**Comment by mahmoud200m** [comment]
done
